#!/bin/bash
# grepip - Grep IP
# by AngelD

# display help banner
if [[ $# -eq 0 && ! -p /dev/stdin ]]; then
  echo "Grep IP - Pull / Exclude IPv4 addresses"
  echo "stdin/out support for workflow integration"
  echo "Usage: 'grepip (<file>) [options] -h, --help'"
  exit
fi

arg_show_help=$(echo 'no')
arg_invert_match=$(echo 'no')
arg_grep_ipv4_and_alike=$(echo 'no')
arg_grep_ipv4_alike=$(echo 'no')
arg_grep_contains_ipv4=$(echo 'no')
arg_color_match=$(echo 'no')
arg_extract_string=$(echo 'no')
argidx=0 # arg index
for arg in $@; do
argidx=$((argidx+1)) # index of arg
validx=$((argidx+1)) # index of arg-value (next arg)
  if [[ '-h' == "${arg}" || '--help' == "${arg}" ]]; then
    arg_show_help=$(echo 'yes')
  elif [[ '-v' == "${arg}" || '--invert-match' == "${arg}" ]]; then
    arg_invert_match=$(echo 'yes')
  elif [[ '-g' == "${arg}" || '--grep-ipv4' == "${arg}" ]]; then
    arg_grep_contains_ipv4=$(echo 'yes')
  elif [[ '-G' == "${arg}" || '--only-ipv4-alike' == "${arg}" ]]; then
    arg_grep_ipv4_alike=$(echo 'yes')
  elif [[ '-c' == "${arg}" || '--color-always' == "${arg}" ]]; then
    arg_color_match=$(echo 'yes')
  elif [[ '-o' == "${arg}" ]]; then
    arg_extract_string=$(echo 'yes')
  fi
done

# display full help
if [[ $arg_show_help == 'yes' ]]; then
  echo "Grep IPv4 Address - Pull / Exclude IPv4 addresses"
  echo "Usage: 'grepip (<file>) [options]'"
  echo "(no-option)                (default) return string matching IPv4"
  echo "  -h, --help               display this help and exit"
  echo "  -g, --ipv4-string        match on string containing IPv4 (IFS='.')"
  echo "  -G, --ipv4-host-string   match on string containing IPv4-alike (IFS='-')"
  echo "  -o, --extract-match      extract matching string (not supported with -v)"
  echo "  -c, --color-match        colorize match (not supported with -v)"
  echo "  -v, --invert-match       exclude matching IPv4 address from result (supported wiht -g|-G)"
  exit
fi

if  [[ $arg_grep_contains_ipv4 == 'yes' && $arg_grep_ipv4_alike == 'yes' ]]; then
  arg_grep_ipv4_and_alike=$(echo 'yes')
  arg_grep_contains_ipv4=$(echo 'no')
  arg_grep_ipv4_alike=$(echo 'no')
fi

data=""
if [[ -p /dev/stdin ]]; then
  data=$(cat "/dev/stdin")
elif [[ $# -gt 0 ]]; then
  data=$(cat $1 | tr ',' '\n')
fi

regex_ipv4=$(echo "(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)")
regex_ipv4_alike=$(echo "[0-9]{1,3}(-)[0-9]{1,3}(-)[0-9]{1,3}(-)[0-9]{1,3}")
regex_ipv4_and_alike=$(echo "[0-9]{1,3}(\.|-)[0-9]{1,3}(\.|-)[0-9]{1,3}(\.|-)[0-9]{1,3}")

# only print the match (<ip address>)
if [[ $arg_invert_match == 'yes' ]]; then
  result=$(echo "$data" | grep -Ev "^${regex_ipv4}$")

  if  [[ $arg_grep_contains_ipv4 == 'yes' ]]; then
    result=$(echo "$result" | grep -Ev "${regex_ipv4}")
  fi

  if  [[ $arg_grep_ipv4_alike == 'yes' ]]; then
    result=$(echo "$result" | grep -Ev "${regex_ipv4_alike}")
  fi

  if  [[ $arg_grep_ipv4_and_alike == 'yes' ]]; then
    result=$(echo "$result" | grep -Ev "${regex_ipv4_and_alike}")
  fi

  if [[ "${#result}" -gt 0 ]]; then
    echo "$result"
  fi

elif  [[ $arg_grep_ipv4_alike == 'yes' ]]; then
  if [[ $arg_invert_match == 'yes' ]]; then
    echo "$data" | grep -Ev "${regex_ipv4_alike}"
  elif [[ $arg_extract_string == 'yes' ]]; then
    echo "$data" | grep -E -o "${regex_ipv4_alike}"
  elif  [[ $arg_color_match == 'yes' ]]; then
      echo "$data" | grep -E "${regex_ipv4_alike}" --color=always
  else
    echo "$data" | grep -E "${regex_ipv4_alike}"
  fi
elif  [[ $arg_grep_contains_ipv4 == 'yes' ]]; then
  if [[ $arg_invert_match == 'yes' ]]; then
    echo "$data" | grep -Ev "${regex_ipv4}"
  elif [[ $arg_extract_string == 'yes' ]]; then
    echo "$data" | grep -E -o "${regex_ipv4}"
  elif  [[ $arg_color_match == 'yes' ]]; then
      echo "$data" | grep -E "${regex_ipv4}" --color=always
  else
    echo "$data" | grep -E "${regex_ipv4}"
  fi
elif [[ $arg_grep_ipv4_and_alike == 'yes' ]]; then
  if [[ $arg_invert_match == 'yes' ]]; then
    echo "$data" | grep -Ev "${regex_ipv4_and_alike}"
  elif [[ $arg_extract_string == 'yes' ]]; then
    echo "$data" | grep -E -o "${regex_ipv4_and_alike}"
  elif  [[ $arg_color_match == 'yes' ]]; then
    echo "$data" | grep -E "${regex_ipv4_and_alike}" --color=always
  else
    echo "$data" | grep -E "${regex_ipv4_and_alike}"
  fi
elif [[ $arg_extract_string == 'yes' ]]; then
  echo "$data" | grep -E -o "${regex_ipv4}"
else
  if  [[ $arg_color_match == 'yes' ]]; then
    echo "$data" | grep -E "^${regex_ipv4}$" --color=always
  else
    echo "$data" | grep -E "^${regex_ipv4}$"
  fi
fi
