#!/bin/bash

if [[ ! -p /dev/stdin && "$#" -eq 0 ]]; then
  echo "missing input (stdin or file)"
  exit 1
fi

arg_from_file=$(echo 'yes')
from_file=""
arg_multi_input=$(echo 'yes')
argidx=0 # arg index
for arg in $@; do
argidx=$((argidx+1)) # index of arg
validx=$((argidx+1)) # index of arg-value (next arg)
  if [[ '-f' == "${arg}" || '--from-file' == "${arg}" ]]; then
    arg_from_file=$(echo 'yes')
    from_file="${!validx}"
  elif [[ '-m' == "${arg}" || '--multi-input' == "${arg}" ]]; then
    arg_multi_input=$(echo 'yes')
 fi
done

if [[ $arg_from_file == 'yes' ]]; then
  if [[ ! -f "$from_file" ]]; then
    echo "missing file -- '$from_file'"
    exit 1
  fi
fi

if [[ $arg_from_file == "yes" ]]; then
  data=$(cat "$from_file" | grep ":")
else
  data=$(cat "/dev/stdin" | grep ":")
fi
#echo "$data"
#echo "----------------------"

json=""
#if [[ $arg_multi_input == 'yes' ]]; then
#  json="["
#fi

json+="{"
if [[ $arg_from_file == "yes" ]]; then
json=$(echo "${json}\"source-file\": \"$from_file\",")
fi
#echo "$data" | grep ":" | while read line; do
while read line; do
hname=$(echo "$line" | cut -d " " -f 1 | sed 's/:.*//g' | tr -d '\r')
#hvalue=$(echo "$line" | cut -d " " -f 2- | tr -d '\r')
hvalue=$(echo "$line" | cut -d " " -f 2- | tr -d '\r' | sed 's/"//g')

json=$(echo "$json\"$hname\": \"$hvalue\",")
done < <(echo "$data" | grep ":")

json=$(echo "$json" | sed 's/,$//g')

json+="}"
#if [[ $arg_multi_input == 'yes' ]]; then
#  json+="]"
#fi
echo $json
