#!/bin/bash
# revasset - Reverse asset (DNS/IP) position
# by AngelD

# display short help
if [[ $# -eq 0 && ! -p /dev/stdin ]]; then
  echo "Reverse Asset - Reverse each '.' position (ex. com.google / 1.0.0.137)."
  echo "Usage: 'rdns (<dns>) -h, --help'"
  exit
fi

arg_show_help=$(echo 'no')
argidx=0 # arg index
for arg in $@; do
argidx=$((argidx+1)) # index of arg
validx=$((argidx+1)) # index of arg-value (next arg)
  if [[ '-h' == "${arg}" || '--help' == "${arg}" ]]; then
    arg_show_help=$(echo 'yes')
 fi
done

#---- validate options ----
if [[ $arg_show_help == 'no' ]]; then
  if [[ -p /dev/stdin ]]; then
    if [[ $# -ne 0 ]]; then
      echo "revasset: invalid option(s) -- '$@'"
      arg_show_help=$(echo 'yes')
    fi
  elif [[ $# -ne 1 ]]; then
    echo "revasset: invalid options -- '$@'"
    arg_show_help=$(echo 'yes')
  fi
fi

#---- display help banner ----
if [[ $arg_show_help == 'yes' ]]; then
  echo "Reverse Asset - Reverse each '.' position (ex. com.google / 1.0.0.127)."
  echo "Usage: 'rdns (<dns>)'"
  echo '  -h, --help              display this help and exit'
  exit
fi

# reverse dns from std input (piped output)
if [ -p /dev/stdin ]; then
  data=$(cat /dev/stdin)
else
  data="$1"
fi

echo "$data" | perl -nle 'print join ".",reverse(split /\./,$_)'
